module.exports = {
  reactStrictMode: true,
  env: {
    MORALIS_APP_ID: process.env.MORALIS_APP_ID,
    MORALIS_SERVER_URL: process.env.MORALIS_SERVER_URL,
    POOL_CONTRACT_ADDRESS_DEV: process.env.POOL_CONTRACT_ADDRESS_DEV,
    PREM_TOKEN_ADDRESSS_DEV: process.env.PREM_TOKEN_ADDRESSS_DEV,
    COVER_TOKEN_ADDRESSS_DEV: process.env.COVER_TOKEN_ADDRESSS_DEV
  }
}
